### PR TITLE
Implement mutual friends

### PR DESCRIPTION
**Pull request by Jmagero**
Requesting for more guidance on how to implement mutual friends

### CODE REVIEW

**Comment by Jmagero** [comment]
Fixed rubocop checks

**Review by ioilmio — CHANGES_REQUESTED** [review]
# Hello @Jmagero Great Job! 💪🏽 
## You come a long road and you are almost there
## You have to fix a couple of stuff and the project will be ready

# Required changes ♻️ 
- ### Fix button
image

- ###  Fix the redirecting behavior for comments and likes; after I submit a comment I get back to home leave, me on the page after refresh maybe I want to make other comments or like some other posts too

- ### Sleep statements in tests are too much this is slowing down your test a lot, remove them please, for future test coverage I can suggest you [simple cov](https://github.com/simplecov-ruby/simplecov) gem
- ###  Style and position better these friend requests, they are poor visible, try to put them to the side 
image

- ### Fix this button 
image

- ### In the friendship model you should update user_id and friend_id for both users with a mutual relationship,e.g. I can't find the friend_id 12 referenced in user1 friendship table.
Screenshot from 2021-02-20 03-47-44

- ### User#friend_requests and  User#pending_friends can be defined as association with SQL query 

## Optional but highly recommended
- ### why not implement a list of friends to show in the user's profile?
- ### Have you read about the n+1 problem? Can you explain it?

## Good luck with these changes, this milestone is pretty challenging, if you have any doubts contact me on slack @illuminatosalvatore

**Comment by Jmagero** [comment]
- [x] Fix button
- [x] Sleep statements in tests are too much this is slowing down your test a lot
- [x] Style and position better these friend requests
- [x] Implement mutual friendship

**Review by GzimAsani — CHANGES_REQUESTED** [review]
# Status: Changes Required :recycle: 

## Very good project and good job implementing almost all the changes requested by previous reviewer :muscle: , however please fix the following:
- [ ] _Fix the redirecting behavior for comments and likes; after I submit a comment I get back to home leave, me on the page after refresh maybe I want to make other comments or like some other posts too_ **This request was not implemented so please fix this redirection**
- [ ] Currently you have 1 rubocop offense please fix that
- [ ] Please add color and border to this button because it is poorly visible tse

### **Please make the required changes and submit another review request when you are ready.**

<hr>
If you have any question kindly reach me on slack @GzimAsani

### HAPPY CODING :computer:

**Comment by Jmagero** [comment]
- [x]Currently, you have 1 rubocop offense please fix that- No rubocop offense found
- [X] Please add color and border to this button because it is poorly visible - Fixed
- [X]Fix the redirecting behavior for comments and likes; after I submit a comment I get back to home leave, me on the page after refresh maybe I want to make other comments or like some other posts too This request was not implemented so please fix this redirection- Checked with the TSE and had no issue

**Review by lekegitrepo — CHANGES_REQUESTED** [review]
## Status: Changes Required! :recycle:
#### Hi @Jmagero :clap: :clap:
##### You have done a good job so far :+1: However, there is still one requirement from the last review that is missing/not implemented correctly. Check my comment below :point_down:

- Fix the redirecting issue as mentioned in the previous reviews. When a user submits a comment or likes a post it should not redirect to the home page.

#### _Reviewed by Temitayo Adeleke_

**Comment by Jmagero** [comment]
- [x] Fix the redirecting issue as mentioned in the previous reviews. When a user submits a comment or likes a post it should not redirect to the home page.- Fixed

**Review by MahmoudBakr23 — APPROVED** [review]
# **Approved ✔✔**

<hr>

Hello there, great job you've done on this project, and on all the previously requested changes, you may now merge and submit. Congratulations 🎉🎉

<hr>

## **[OPTIONAL but highly recommended]** 
- Please take a minute of your time and remove the line ```rails db:drop``` from your readme file before the ```rails db:create``` since there's no created database yet, how is it possible to drop/delete it?!

<hr>

Good luck with the next and happy coding 👨‍💻💻

**Pull request merged**
